export const ADMIN_PRODUCT_LIST_REQUEST = "ADMIN_PRODUCT_LIST_REQUEST";
export const ADMIN_PRODUCT_LIST_SUCCESS = "ADMIN_PRODUCT_LIST_SUCCESS";
export const ADMIN_PRODUCT_LIST_FALIS = "ADMIN_PRODUCT_LIST_FALIS";

export const ADMIN_PRODUCT_ADD_REQUEST = "ADMIN_PRODUCT_ADD_REQUEST";
export const ADMIN_PRODUCT_ADD_SUCCESS = "ADMIN_PRODUCT_ADD_SUCCESS";
export const ADMIN_PRODUCT_ADD_FALIS = "ADMIN_PRODUCT_ADD_FALIS";